"""Structured Cambridge Academic Writing prompts sourced from public web archives."""

from typing import Any


CAMBRIDGE_17_SOURCE_URL = "https://blog.scitudy.com/2025/02/17/cambridge-ielts-17-writing-tests1-4-with-samples/"
CAMBRIDGE_18_SOURCE_URL = "https://blog.scitudy.com/2023/11/27/cambridgeielts-18-writing-tests1-4-with-samples/"
CAMBRIDGE_19_SOURCE_URL = "https://blog.scitudy.com/2025/02/17/cambridge-ielts-19-writing-tests1-4-with-samples/"


def _task1(
    *,
    book: int,
    test: int,
    slug: str,
    short_title: str,
    lines: list[str],
    format_type: str,
    tags: list[str],
    image_url: str,
    image_width: int,
    image_height: int,
    source_page_url: str,
) -> dict[str, Any]:
    return {
        "slug": slug,
        "task_type": "task1",
        "title": f"Cambridge {book} Test {test} · {short_title}",
        "prompt_text": "\n\n".join(lines),
        "prompt_details": {
            "format": format_type,
            "cambridge_book": book,
            "cambridge_test": test,
            "topic_tags": tags,
            "source_label": "Scitudy public Cambridge writing archive",
            "source_page_url": source_page_url,
            "chart_image": {
                "url": image_url,
                "width": image_width,
                "height": image_height,
                "alt": short_title,
            },
        },
        "source": "cambridge_scitudy",
    }


def _task2(
    *,
    book: int,
    test: int,
    slug: str,
    short_title: str,
    lines: list[str],
    essay_type: str,
    tags: list[str],
    source_page_url: str,
) -> dict[str, Any]:
    return {
        "slug": slug,
        "task_type": "task2",
        "title": f"Cambridge {book} Test {test} · {short_title}",
        "prompt_text": "\n\n".join(lines),
        "prompt_details": {
            "cambridge_book": book,
            "cambridge_test": test,
            "essay_type": essay_type,
            "topic_tags": tags,
            "source_label": "Scitudy public Cambridge writing archive",
            "source_page_url": source_page_url,
        },
        "source": "cambridge_scitudy",
    }


CAMBRIDGE_ACADEMIC_WRITING_PROMPTS: list[dict[str, Any]] = [
    _task1(
        book=17,
        test=1,
        slug="cambridge-17-test-1-task-1-norbiton-site-redevelopment",
        short_title="Norbiton Site Redevelopment",
        lines=[
            "The maps below show an industrial area in the town of Norbiton, and planned future development of the site.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="map",
        tags=["urban_planning", "housing", "infrastructure"],
        image_url="https://blogimg.scitudy.com/2025/02/image-2.png",
        image_width=838,
        image_height=912,
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task2(
        book=17,
        test=1,
        slug="cambridge-17-test-1-task-2-taking-risks",
        short_title="Taking Risks",
        lines=[
            "It is important for people to take risks, both in their professional lives and their personal lives.",
            "Do you think the advantages of taking risks outweigh the disadvantages?",
            "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
            "Write at least 250 words.",
        ],
        essay_type="outweigh",
        tags=["work", "personal_growth", "decision_making"],
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task1(
        book=17,
        test=2,
        slug="cambridge-17-test-2-task-1-police-budget",
        short_title="Police Budget Sources and Spending",
        lines=[
            "The table and charts below give information on the police budget for 2017 and 2018 in one area of Britain. The table shows where the money came from and the charts show how it was distributed.",
            "Summarize the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="mixed_table_pie",
        tags=["government", "budget", "public_services"],
        image_url="https://blogimg.scitudy.com/2025/02/image-5-861x1024.png",
        image_width=861,
        image_height=1024,
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task2(
        book=17,
        test=2,
        slug="cambridge-17-test-2-task-2-children-smartphones",
        short_title="Children and Smartphones",
        lines=[
            "Some children spend hours every day on their smartphones.",
            "Why is this the case? Do you think this is a positive or a negative development?",
            "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
            "Write at least 250 words.",
        ],
        essay_type="causes_positive_negative",
        tags=["children", "technology", "education"],
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task1(
        book=17,
        test=3,
        slug="cambridge-17-test-3-task-1-weekly-family-spending",
        short_title="Weekly Family Spending",
        lines=[
            "The chart below gives information about how families in one country spent their weekly income in 1968 and in 2018.",
            "Summarize the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="bar_chart",
        tags=["household_spending", "consumer_behavior", "comparison"],
        image_url="https://blogimg.scitudy.com/2025/02/image-6-1024x907.png",
        image_width=1024,
        image_height=907,
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task2(
        book=17,
        test=3,
        slug="cambridge-17-test-3-task-2-working-abroad-after-training",
        short_title="Working Abroad After Training",
        lines=[
            "Some people believe that professionals, such as doctors and engineers, should be required to work in the country where they did their training. Others believe they should be free to work in another country if they wish.",
            "Discuss both these views and give your own opinion.",
            "Write at least 250 words.",
        ],
        essay_type="discuss_both_views",
        tags=["migration", "professionals", "policy"],
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task1(
        book=17,
        test=4,
        slug="cambridge-17-test-4-task-1-shop-closures-and-openings",
        short_title="Shop Closures and Openings",
        lines=[
            "The graph below shows the number of shops that closed and the number of new shops that opened in one country between 2011 and 2018.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="line_graph",
        tags=["retail", "business", "time_series"],
        image_url="https://blogimg.scitudy.com/2025/02/image.png",
        image_width=769,
        image_height=492,
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task2(
        book=17,
        test=4,
        slug="cambridge-17-test-4-task-2-alternative-medicine",
        short_title="Alternative Medicine",
        lines=[
            "Nowadays, a growing number of people with health problems are trying alternative medicines and treatments instead of visiting their usual doctor.",
            "Do you think this is a positive or a negative development?",
            "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
            "Write at least 250 words.",
        ],
        essay_type="positive_negative",
        tags=["health", "medicine", "society"],
        source_page_url=CAMBRIDGE_17_SOURCE_URL,
    ),
    _task1(
        book=18,
        test=1,
        slug="cambridge-18-test-1-task-1-urban-population-asia",
        short_title="Urban Population in Four Asian Countries",
        lines=[
            "The graph below gives information about the percentage of the population in four Asian countries living in cities from 1970 to 2020, with predictions for 2030 and 2040.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="line_graph",
        tags=["urbanization", "asia", "population"],
        image_url="https://blog.scitudy.com/wp-content/uploads/2023/11/ielts18-test1-task1-1-1024x779.png",
        image_width=1024,
        image_height=779,
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task2(
        book=18,
        test=1,
        slug="cambridge-18-test-1-task-2-science-and-peoples-lives",
        short_title="Science and People's Lives",
        lines=[
            "The most important aim of science should be to improve people's lives.",
            "To what extent do you agree or disagree with this statement?",
            "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
            "Write at least 250 words.",
        ],
        essay_type="agree_disagree",
        tags=["science", "ethics", "society"],
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task1(
        book=18,
        test=2,
        slug="cambridge-18-test-2-task-1-us-household-income",
        short_title="US Households by Annual Income",
        lines=[
            "The chart below shows the number of households in the US by their annual income in 2007, 2011 and 2015.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="bar_chart",
        tags=["income", "households", "us"],
        image_url="https://blog.scitudy.com/wp-content/uploads/2023/11/ielts18test2-write1-2-1024x667.png",
        image_width=1024,
        image_height=667,
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task2(
        book=18,
        test=2,
        slug="cambridge-18-test-2-task-2-main-subject-vs-other-subjects",
        short_title="Main Subject vs Other Subjects",
        lines=[
            "Some university students want to learn about other subjects in addition to their main subjects. Others believe it is more important to give all their time and attention to studying for a qualification.",
            "Discuss both these views and give your own opinion.",
            "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
            "Write at least 250 words.",
        ],
        essay_type="discuss_both_views",
        tags=["education", "university", "curriculum"],
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task1(
        book=18,
        test=3,
        slug="cambridge-18-test-3-task-1-public-library-floor-plan",
        short_title="Public Library Floor Plan Changes",
        lines=[
            "The diagram below shows the floor plan of a public library 20 years ago and how it looks now.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="map",
        tags=["library", "floor_plan", "renovation"],
        image_url="https://blog.scitudy.com/wp-content/uploads/2023/11/ielts18-test3-write1-2-925x1024.png",
        image_width=925,
        image_height=1024,
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task2(
        book=18,
        test=3,
        slug="cambridge-18-test-3-task-2-rural-to-city-migration",
        short_title="Rural to City Migration",
        lines=[
            "In many countries around the world, rural people are moving to cities, so the population in the countryside is decreasing.",
            "Do you think this is a positive or a negative development?",
            "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
            "Write at least 250 words.",
        ],
        essay_type="positive_negative",
        tags=["urbanization", "migration", "society"],
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task1(
        book=18,
        test=4,
        slug="cambridge-18-test-4-task-1-metal-price-changes",
        short_title="Monthly Changes in Metal Prices",
        lines=[
            "The graph below shows the average monthly change in the prices of three metals during 2014.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="line_graph",
        tags=["commodities", "prices", "metals"],
        image_url="https://blog.scitudy.com/wp-content/uploads/2023/11/cambridge-ielts-18-test4-writing1-1024x808.png",
        image_width=1024,
        image_height=808,
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task2(
        book=18,
        test=4,
        slug="cambridge-18-test-4-task-2-ageing-population",
        short_title="Ageing Population",
        lines=[
            "In many countries, people are now living longer than ever before. Some people say an ageing population creates problems for governments. Other people think there are benefits if society has more elderly people.",
            "To what extent do the advantages of having an ageing population outweigh the disadvantages?",
            "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
            "Write at least 250 words.",
        ],
        essay_type="outweigh",
        tags=["ageing", "government", "society"],
        source_page_url=CAMBRIDGE_18_SOURCE_URL,
    ),
    _task1(
        book=19,
        test=1,
        slug="cambridge-19-test-1-task-1-social-centre-activities",
        short_title="Social Centre Activity Participation",
        lines=[
            "The line graph below gives information on the numbers of participants for different activities at one social centre in Melbourne, Australia for the period 2000 to 2020.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="line_graph",
        tags=["social_centre", "activities", "participation"],
        image_url="https://blogimg.scitudy.com/2025/02/image-7.png",
        image_width=1024,
        image_height=622,
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
    _task2(
        book=19,
        test=1,
        slug="cambridge-19-test-1-task-2-competition-vs-cooperation",
        short_title="Competition vs Cooperation",
        lines=[
            "Some people think that competition at work, at school and in daily life is a good thing. Others believe that we should try to cooperate more, rather than competing against each other.",
            "Discuss both these views and give your own opinion.",
            "Write at least 250 words.",
        ],
        essay_type="discuss_both_views",
        tags=["education", "work", "society"],
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
    _task1(
        book=19,
        test=2,
        slug="cambridge-19-test-2-task-1-harbour-plan-changes",
        short_title="Harbour Plan Changes",
        lines=[
            "The plans below show a harbour in 2000 and how it looks today.",
            "Summarize the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="map",
        tags=["harbour", "redevelopment", "tourism"],
        image_url="https://blogimg.scitudy.com/2025/02/image-8.png",
        image_width=548,
        image_height=805,
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
    _task2(
        book=19,
        test=2,
        slug="cambridge-19-test-2-task-2-shorter-working-week",
        short_title="Shorter Working Week",
        lines=[
            "The working week should be shorter and workers should have a longer weekend.",
            "Do you agree or disagree?",
            "Write at least 250 words.",
        ],
        essay_type="agree_disagree",
        tags=["work", "labor_policy", "wellbeing"],
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
    _task1(
        book=19,
        test=3,
        slug="cambridge-19-test-3-task-1-ethanol-production",
        short_title="Ethanol Production Process",
        lines=[
            "The diagram below shows how a biofuel called ethanol is produced.",
            "Summarize the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="process_diagram",
        tags=["biofuel", "ethanol", "production"],
        image_url="https://blogimg.scitudy.com/2025/02/image-9.png",
        image_width=736,
        image_height=818,
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
    _task2(
        book=19,
        test=3,
        slug="cambridge-19-test-3-task-2-saving-money-for-the-future",
        short_title="Saving Money for the Future",
        lines=[
            "It is important for everyone, including young people, to save money for their future.",
            "To what extent do you agree or disagree with this statement?",
            "Write at least 250 words.",
        ],
        essay_type="agree_disagree",
        tags=["money", "youth", "future_planning"],
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
    _task1(
        book=19,
        test=4,
        slug="cambridge-19-test-4-task-1-dance-classes",
        short_title="Dance Classes by Location and Type",
        lines=[
            "The charts below give information on the location and types of dance classes young people in a town in Australia are currently attending.",
            "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
            "Write at least 150 words.",
        ],
        format_type="mixed_charts",
        tags=["dance", "youth", "australia"],
        image_url="https://blogimg.scitudy.com/2025/02/image-10.png",
        image_width=675,
        image_height=782,
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
    _task2(
        book=19,
        test=4,
        slug="cambridge-19-test-4-task-2-global-food-supply",
        short_title="Global Food Supply",
        lines=[
            "In many countries nowadays, consumers can go to a supermarket and buy food produced all over the world.",
            "Do you think this is a positive or a negative development?",
            "Write at least 250 words.",
        ],
        essay_type="positive_negative",
        tags=["food", "globalization", "consumers"],
        source_page_url=CAMBRIDGE_19_SOURCE_URL,
    ),
]
